#!/usr/bin/env sh

# # bar settings
# yabai -m config status_bar                   off
# # yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# # yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# # yabai -m config status_bar_background_color  0xff202020
# # yabai -m config status_bar_foreground_color  0xffa8a8a8
# # yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# # yabai -m config status_bar_power_icon_strip   
# # yabai -m config status_bar_space_icon        
# # yabai -m config status_bar_clock_icon        

# # global settings
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config window_placement             second_child
# yabai -m config window_topmost               off
# yabai -m config window_opacity               off
# # yabai -m config window_opacity_duration      0.0
# yabai -m config window_shadow                on
# yabai -m config window_border                on
# yabai -m config window_border_placement      inset
# yabai -m config window_border_width          2
# yabai -m config window_border_radius         -1.0
# yabai -m config active_window_border_topmost off
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f
# # yabai -m config active_window_opacity        1.0
# # yabai -m config normal_window_opacity        0.90
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# # yabai -m config mouse_modifier               fn
# # yabai -m config mouse_action1                move
# # yabai -m config mouse_action2                resize

# # general space settings
# yabai -m config layout                       bsp
# yabai -m config top_padding                  5
# yabai -m config bottom_padding               5
# yabai -m config left_padding                 5
# yabai -m config right_padding                5
# yabai -m config window_gap                   5

# echo "yabai configuration loaded.."


# ====== Variables =============================

gaps_top="4"
gaps_bottom="4"
gaps_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

bar_bg_color="202020"
bar_fg_color="a8a8a8"

# ====== Bar settings =============================

yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica:Bold:12.0"
yabai -m config status_bar_background_color  "0xff${bar_bg_color}"
yabai -m config status_bar_foreground_color  "0xff${bar_fg_color}"
yabai -m config status_bar_space_icon_strip  🏠 👀 💻 💖 ✏️ 🌱
yabai -m config status_bar_clock_icon

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         autofocus

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== List of rules =========================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off

# ====== Space specific settings =======================

yabai -m config --space 6 layout float
